services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=abc123
    ports:
      - "5434:5432"
    volumes:
      - /var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: mayito@mayito.com
      PGADMIN_DEFAULT_PASSWORD: abc123
    ports:
      - "8081:80"
    depends_on:
      - postgres

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=abc123
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb/data
